name: CI Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macOS-latest]
        os: [ubuntu-latest]
        rust: [stable]

    steps:
      - name: Install Rust toolchain
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}

      - name: Checkout the repository
        uses: actions/checkout@master

      - name: Run build scripts
        id: run_build_scripts
        run: cargo build --release

      - name: Upload release asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.run_build_scripts.outputs.upload_url }}
          asset_path: ./target/release/cwim
          asset_name: cwim
          asset_content_type: application/x-sharedlib
